mysql:
    host: '127.0.0.1'
    port: 3306
    user: root
    pass: 123456
    db: messagequeue

mongodb:
    host: '127.0.0.1'
    port: 27017
    database: 'messagequeue'

memcache:
    host: 127.0.0.1
    port: 11211
